### ISSUE TITLE
Building btc error

### ISSUE THREAD

**Issue by juchao1989** [gyk001/viabtc_exchange_server_docker#2]
Building btc
Step 1/25 : FROM ubuntu:xenial AS btc-build
ERROR: Service 'btc' failed to build: Error parsing reference: "ubuntu:xenial AS btc-build" is not a valid repository/tag: invalid reference format

**Comment by lealife** [comment]
`FROM ubuntu:xenial AS btc-build` 改成 `ubuntu:xenial` 即可
查看我的PR: https://github.com/gyk001/viabtc_exchange_server_docker/pull/4

**Comment by gyk001** [comment]
应该是你用的Docker版本太低，Docker 17.05.0-ce以上版本支持多阶段构建了 😄 
https://docs.docker.com/develop/develop-images/multistage-build/#name-your-build-stages

**Comment by lealife** [comment]
@gyk001 原来是这个问题, 多谢!!
还有, 我的PR里面 Kafka 的配置 `KAFKA_ADVERTISED_HOST` 貌似不支持了, 得要 `KAFKA_ADVERTISED_HOST_NAME`
